package minestrapp.guide;

import minestrapp.ItemsRegistry;
import minestrapp.Minestrappolation;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import werty.guidance.gui.EnumPageType;
import werty.guidance.gui.GuideEntry;
import werty.guidance.gui.GuideGroup;
import werty.guidance.gui.GuideInfoPage;
import werty.guidance.gui.GuideManager;

public class GuideHandler {
	public static GuideManager manager = new GuideManager();
	
	public static GuideGroup basics = new GuideGroup("Game Mechanics");
	public static GuideGroup plant = new GuideGroup("Organic Blocks");
	public static GuideGroup soil = new GuideGroup("Soil Blocks");
	public static GuideGroup frost = new GuideGroup("Frozen Blocks");
	public static GuideGroup stone = new GuideGroup("Stone Blocks");
	public static GuideGroup ore = new GuideGroup("Ores");
	public static GuideGroup resource = new GuideGroup("Resource Storage Blocks");
	public static GuideGroup glass = new GuideGroup("Glass Blocks");
	public static GuideGroup misc_building = new GuideGroup("Misc. Building Blocks");
	public static GuideGroup wood_building = new GuideGroup("Wood Building Blocks");
	public static GuideGroup stone_building = new GuideGroup("Stone Building Blocks");
	public static GuideGroup decor = new GuideGroup("Decorative Blocks");
	public static GuideGroup utility = new GuideGroup("Utility Blocks");
	public static GuideGroup redstone = new GuideGroup("Redstone Mechanisms");
	public static GuideGroup machine = new GuideGroup("Tool/Machine Blocks");
	public static GuideGroup crops = new GuideGroup("Seeds & Crops");
	public static GuideGroup materials = new GuideGroup("Raw Materials");
	public static GuideGroup mob_loot = new GuideGroup("Mob Loot");
	public static GuideGroup ingredients = new GuideGroup("Crafting Ingredients");
	public static GuideGroup food = new GuideGroup("Foodstuffs");
	public static GuideGroup potions = new GuideGroup("Potions");
	public static GuideGroup enchant = new GuideGroup("Enchantments");
	public static GuideGroup transport = new GuideGroup("Transportation Items");
	public static GuideGroup tool = new GuideGroup("Tools");
	public static GuideGroup special_tool = new GuideGroup("Specialty Tools");
	public static GuideGroup weapon = new GuideGroup("Weapons");
	public static GuideGroup special_weapon = new GuideGroup("Specialty Weapons");
	public static GuideGroup armor = new GuideGroup("Armor");
	
	public static void preInit(){
		manager.textColor = 0;
		
		manager.imgGuide = new ResourceLocation(Minestrappolation.MODID+":textures/gui/guide.png");
		manager.imgGuideBG = new ResourceLocation(Minestrappolation.MODID+":textures/gui/guideBG.png");
		
		manager.registerEntryGroup(basics);
		manager.registerEntryGroup(plant);
		manager.registerEntryGroup(soil);
		manager.registerEntryGroup(frost);
		manager.registerEntryGroup(stone);
		manager.registerEntryGroup(ore);
		manager.registerEntryGroup(resource);
		manager.registerEntryGroup(glass);
		manager.registerEntryGroup(misc_building);
		manager.registerEntryGroup(wood_building);
		manager.registerEntryGroup(stone_building);
		manager.registerEntryGroup(decor);
		manager.registerEntryGroup(utility);
		manager.registerEntryGroup(redstone);
		manager.registerEntryGroup(machine);
		manager.registerEntryGroup(crops);
		manager.registerEntryGroup(materials);
		manager.registerEntryGroup(mob_loot);
		manager.registerEntryGroup(ingredients);
		manager.registerEntryGroup(food);
		manager.registerEntryGroup(potions);
		manager.registerEntryGroup(enchant);
		manager.registerEntryGroup(transport);
		manager.registerEntryGroup(tool);
		manager.registerEntryGroup(special_tool);
		manager.registerEntryGroup(weapon);
		manager.registerEntryGroup(special_weapon);
		manager.registerEntryGroup(armor);
		
		basics.addEntry(new GuideEntry("minechiridion", "Minechiridion", new ItemStack(ItemsRegistry.minechiridion), 32+(0*16), 32));
		manager.registerInfoPage("minechiridion", new GuideInfoPage("minechiridion", EnumPageType.INFO));
		
		plant.addEntry(new GuideEntry("tallgrass", "Tallgrass", new ItemStack(Blocks.TALLGRASS, 0, 1), 32+(0*16), 32));
		manager.registerInfoPage("tallgrass", new GuideInfoPage("tallgrass", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("double_tallgrass", "Double Tallgrass", new ItemStack(Blocks.DOUBLE_PLANT, 0, 2), 32+(1*16), 32));
		manager.registerInfoPage("double_tallgrass", new GuideInfoPage("double_tallgrass", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("fern", "Fern", new ItemStack(Blocks.TALLGRASS, 0, 2), 32+(2*16), 32));
		manager.registerInfoPage("fern", new GuideInfoPage("fern", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("double_fern", "Large Fern", new ItemStack(Blocks.DOUBLE_PLANT, 0, 3), 32+(3*16), 32));
		manager.registerInfoPage("double_fern", new GuideInfoPage("double_fern", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("deadbush", "Dead Bush", new ItemStack(Blocks.DEADBUSH), 32+(4*16), 32));
		manager.registerInfoPage("deadbush", new GuideInfoPage("deadbush", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("dandelion", "Dandelion", new ItemStack(Blocks.YELLOW_FLOWER), 32+(5*16), 32));
		manager.registerInfoPage("dandelion", new GuideInfoPage("dandelion", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("poppy", "Poppy", new ItemStack(Blocks.RED_FLOWER, 0, 0), 32+(6*16), 32));
		manager.registerInfoPage("poppy", new GuideInfoPage("poppy", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("orchid", "Blue Orchid", new ItemStack(Blocks.RED_FLOWER, 0, 1), 32+(7*16), 32));
		manager.registerInfoPage("orchid", new GuideInfoPage("orchid", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("allium", "Allium", new ItemStack(Blocks.RED_FLOWER, 0, 2), 32+(8*16), 32));
		manager.registerInfoPage("allium", new GuideInfoPage("allium", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("azure_bluet", "Azure Bluet", new ItemStack(Blocks.RED_FLOWER, 0, 3), 32+(9*16), 32));
		manager.registerInfoPage("azure_bluet", new GuideInfoPage("azure_bluet", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("red_tulip", "Red Tulip", new ItemStack(Blocks.RED_FLOWER, 0, 4), 32+(10*16), 32));
		manager.registerInfoPage("red_tulip", new GuideInfoPage("red_tulip", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("orange_tulip", "Orange Tulip", new ItemStack(Blocks.RED_FLOWER, 0, 5), 32+(11*16), 32));
		manager.registerInfoPage("orange_tulip", new GuideInfoPage("orange_tulip", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("white_tulip", "White Tulip", new ItemStack(Blocks.RED_FLOWER, 0, 6), 32+(12*16), 32));
		manager.registerInfoPage("white_tulip", new GuideInfoPage("white_tulip", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("pink_tulip", "Pink Tulip", new ItemStack(Blocks.RED_FLOWER, 0, 7), 32+(13*16), 32));
		manager.registerInfoPage("pink_tulip", new GuideInfoPage("pink_tulip", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("oxeye_daisy", "Oxeye Daisy", new ItemStack(Blocks.RED_FLOWER, 0, 8), 32+(14*16), 32));
		manager.registerInfoPage("oxeye_daisy", new GuideInfoPage("oxeye_daisy", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("sunflower", "Sunflower", new ItemStack(Blocks.DOUBLE_PLANT, 0, 0), 32+(15*16), 32));
		manager.registerInfoPage("sunflower", new GuideInfoPage("sunflower", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("lilac", "Lilac", new ItemStack(Blocks.DOUBLE_PLANT, 0, 1), 32+(0*16), 58));
		manager.registerInfoPage("lilac", new GuideInfoPage("lilac", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("rose_bush", "Rose Bush", new ItemStack(Blocks.DOUBLE_PLANT, 0, 4), 32+(1*16), 58));
		manager.registerInfoPage("rose_bush", new GuideInfoPage("rose_bush", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("peony", "Peony", new ItemStack(Blocks.DOUBLE_PLANT, 0, 5), 32+(2*16), 58));
		manager.registerInfoPage("peony", new GuideInfoPage("peony", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("red_mushroom", "Red Mushroom", new ItemStack(Blocks.RED_MUSHROOM), 32+(3*16), 58));
		manager.registerInfoPage("red_mushroom", new GuideInfoPage("red_mushroom", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("brown_mushroom", "Brown Mushroom", new ItemStack(Blocks.BROWN_MUSHROOM), 32+(4*16), 58));
		manager.registerInfoPage("brown_mushroom", new GuideInfoPage("brown_mushroom", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("oak_sapling", "Oak Sapling", new ItemStack(Blocks.SAPLING, 0, 0), 32+(5*16), 58));
		manager.registerInfoPage("oak_sapling", new GuideInfoPage("oak_sapling", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("spruce_sapling", "Spruce Sapling", new ItemStack(Blocks.SAPLING, 0, 1), 32+(6*16), 58));
		manager.registerInfoPage("spruce_sapling", new GuideInfoPage("spruce_sapling", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("birch_sapling", "Birch Sapling", new ItemStack(Blocks.SAPLING, 0, 2), 32+(7*16), 58));
		manager.registerInfoPage("birch_sapling", new GuideInfoPage("birch_sapling", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("jungle_sapling", "Jungle Sapling", new ItemStack(Blocks.SAPLING, 0, 3), 32+(8*16), 58));
		manager.registerInfoPage("jungle_sapling", new GuideInfoPage("jungle_sapling", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("acacia_sapling", "Acacia Sapling", new ItemStack(Blocks.SAPLING, 0, 4), 32+(9*16), 58));
		manager.registerInfoPage("acacia_sapling", new GuideInfoPage("acacia_sapling", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("dark_oak_sapling", "Dark Oak Sapling", new ItemStack(Blocks.SAPLING, 0, 5), 32+(10*16), 58));
		manager.registerInfoPage("dark_oak_sapling", new GuideInfoPage("dark_oak_sapling", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("oak_leaves", "Oak Leaves", new ItemStack(Blocks.LEAVES, 0, 0), 32+(11*16), 58));
		manager.registerInfoPage("oak_leaves", new GuideInfoPage("oak_leaves", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("spruce_leaves", "Spruce Leaves", new ItemStack(Blocks.LEAVES, 0, 1), 32+(12*16), 58));
		manager.registerInfoPage("spruce_leaves", new GuideInfoPage("spruce_leaves", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("birch_leaves", "Birch Leaves", new ItemStack(Blocks.LEAVES, 0, 2), 32+(13*16), 58));
		manager.registerInfoPage("birch_leaves", new GuideInfoPage("birch_leaves", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("jungle_leaves", "Jungle Leaves", new ItemStack(Blocks.LEAVES, 0, 3), 32+(14*16), 58));
		manager.registerInfoPage("jungle_leaves", new GuideInfoPage("jungle_leaves", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("acacia_leaves", "Acacia Leaves", new ItemStack(Blocks.LEAVES2, 0, 0), 32+(15*16), 58));
		manager.registerInfoPage("acacia_leaves", new GuideInfoPage("acacia_leaves", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("dark_oak_leaves", "Dark Oak Leaves", new ItemStack(Blocks.LEAVES2, 0, 1), 32+(0*16), 84));
		manager.registerInfoPage("dark_oak_leaves", new GuideInfoPage("dark_oak_leaves", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("sponge", "Sponge", new ItemStack(Blocks.SPONGE, 0, 1), 32+(1*16), 84));
		manager.registerInfoPage("sponge", new GuideInfoPage("sponge", EnumPageType.INFO));
		plant.addEntry(new GuideEntry("wet_sponge", "Wet Sponge", new ItemStack(Blocks.SPONGE, 0, 1), 32+(2*16), 84));
		manager.registerInfoPage("wet_sponge", new GuideInfoPage("wet_sponge", EnumPageType.INFO));
		
		soil.addEntry(new GuideEntry("dirt", "Dirt", new ItemStack(Blocks.DIRT, 0, 0), 32+(0*16), 32));
		manager.registerInfoPage("dirt", new GuideInfoPage("dirt", EnumPageType.INFO));
		soil.addEntry(new GuideEntry("coarse_dirt", "Coarse Dirt", new ItemStack(Blocks.DIRT, 0, 1), 32+(1*16), 32));
		manager.registerInfoPage("coarse_dirt", new GuideInfoPage("coarse_dirt", EnumPageType.INFO));
		soil.addEntry(new GuideEntry("grass", "Grass", new ItemStack(Blocks.GRASS), 32+(2*16), 32));
		manager.registerInfoPage("grass", new GuideInfoPage("grass", EnumPageType.INFO));
		soil.addEntry(new GuideEntry("podzol", "Podzol", new ItemStack(Blocks.DIRT, 0, 2), 32+(3*16), 32));
		manager.registerInfoPage("podzol", new GuideInfoPage("podzol", EnumPageType.INFO));
		soil.addEntry(new GuideEntry("sand", "Sand", new ItemStack(Blocks.SAND, 0, 0), 32+(4*16), 32));
		manager.registerInfoPage("sand", new GuideInfoPage("sand", EnumPageType.INFO));
		soil.addEntry(new GuideEntry("red_sand", "Red Sand", new ItemStack(Blocks.SAND, 0, 1), 32+(5*16), 32));
		manager.registerInfoPage("red_sand", new GuideInfoPage("red_sand", EnumPageType.INFO));
		soil.addEntry(new GuideEntry("gravel", "Gravel", new ItemStack(Blocks.GRAVEL), 32+(6*16), 32));
		manager.registerInfoPage("gravel", new GuideInfoPage("gravel", EnumPageType.INFO));
		
		stone.addEntry(new GuideEntry("stone", "Stone", new ItemStack(Blocks.STONE, 1, 0), 32+(0*16), 32));
		manager.registerInfoPage("stone", new GuideInfoPage("stone", EnumPageType.INFO));
		stone.addEntry(new GuideEntry("granite", "Granite", new ItemStack(Blocks.STONE, 1, 1), 32+(1*16), 32));
		manager.registerInfoPage("granite", new GuideInfoPage("granite", EnumPageType.INFO));
		stone.addEntry(new GuideEntry("diorite", "Diorite", new ItemStack(Blocks.STONE, 1, 3), 32+(2*16), 32));
		manager.registerInfoPage("diorite", new GuideInfoPage("diorite", EnumPageType.INFO));
		stone.addEntry(new GuideEntry("andesite", "Andesite", new ItemStack(Blocks.STONE, 1, 5), 32+(3*16), 32));
		manager.registerInfoPage("andesite", new GuideInfoPage("andesite", EnumPageType.INFO));
		stone.addEntry(new GuideEntry("sandstone", "Sandstone", new ItemStack(Blocks.SANDSTONE, 0, 0), 32+(4*16), 32));
		manager.registerInfoPage("sandstone", new GuideInfoPage("sandstone", EnumPageType.INFO));
		stone.addEntry(new GuideEntry("bedrock", "Bedrock", new ItemStack(Blocks.BEDROCK), 32+(5*16), 32));
		manager.registerInfoPage("bedrock", new GuideInfoPage("bedrock", EnumPageType.INFO));
		
		ore.addEntry(new GuideEntry("coal_ore", "Coal Ore", new ItemStack(Blocks.COAL_ORE), 32+(0*16), 32));
		manager.registerInfoPage("coal_ore", new GuideInfoPage("coal_ore", EnumPageType.INFO));
		ore.addEntry(new GuideEntry("iron_ore", "Iron Ore", new ItemStack(Blocks.IRON_ORE), 32+(1*16), 32));
		manager.registerInfoPage("iron_ore", new GuideInfoPage("iron_ore", EnumPageType.INFO));
		ore.addEntry(new GuideEntry("gold_ore", "Gold Ore", new ItemStack(Blocks.GOLD_ORE), 32+(2*16), 32));
		manager.registerInfoPage("gold_ore", new GuideInfoPage("gold_ore", EnumPageType.INFO));
		ore.addEntry(new GuideEntry("lapis_ore", "Lapis Lazuli Ore", new ItemStack(Blocks.LAPIS_ORE), 32+(3*16), 32));
		manager.registerInfoPage("lapis_ore", new GuideInfoPage("lapis_ore", EnumPageType.INFO));
		
		resource.addEntry(new GuideEntry("iron_block", "Block of Iron", new ItemStack(Blocks.IRON_BLOCK), 32+(0*16), 32));
		manager.registerInfoPage("iron_block", new GuideInfoPage("iron_block", EnumPageType.INFO));
		resource.addEntry(new GuideEntry("gold_block", "Block of Gold", new ItemStack(Blocks.GOLD_BLOCK), 32+(1*16), 32));
		manager.registerInfoPage("gold_block", new GuideInfoPage("gold_block", EnumPageType.INFO));
		resource.addEntry(new GuideEntry("lapis_block", "Lapis Lazuli Block", new ItemStack(Blocks.LAPIS_BLOCK), 32+(2*16), 32));
		manager.registerInfoPage("lapis_block", new GuideInfoPage("lapis_block", EnumPageType.INFO));
		
		glass.addEntry(new GuideEntry("glass", "Glass", new ItemStack(Blocks.GLASS), 32+(0*16), 32));
		manager.registerInfoPage("glass", new GuideInfoPage("glass", EnumPageType.INFO));
		
		misc_building.addEntry(new GuideEntry("white_wool", "Wool", new ItemStack(Blocks.WOOL, 1, 0), 32+(0*16), 32));
		manager.registerInfoPage("white_wool", new GuideInfoPage("white_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("light_gray_wool", "Light Gray Wool", new ItemStack(Blocks.WOOL, 1, 8), 32+(1*16), 32));
		manager.registerInfoPage("light_gray_wool", new GuideInfoPage("light_gray_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("gray_wool", "Gray Wool", new ItemStack(Blocks.WOOL, 1, 7), 32+(2*16), 32));
		manager.registerInfoPage("gray_wool", new GuideInfoPage("gray_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("black_wool", "Black Wool", new ItemStack(Blocks.WOOL, 1, 15), 32+(3*16), 32));
		manager.registerInfoPage("black_wool", new GuideInfoPage("black_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("brown_wool", "Brown Wool", new ItemStack(Blocks.WOOL, 1, 12), 32+(4*16), 32));
		manager.registerInfoPage("brown_wool", new GuideInfoPage("brown_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("red_wool", "Red Wool", new ItemStack(Blocks.WOOL, 1, 14), 32+(5*16), 32));
		manager.registerInfoPage("red_wool", new GuideInfoPage("red_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("orange_wool", "Orange Wool", new ItemStack(Blocks.WOOL, 1, 1), 32+(6*16), 32));
		manager.registerInfoPage("orange_wool", new GuideInfoPage("orange_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("yellow_wool", "Yellow Wool", new ItemStack(Blocks.WOOL, 1, 4), 32+(7*16), 32));
		manager.registerInfoPage("yellow_wool", new GuideInfoPage("yellow_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("lime_wool", "Lime Wool", new ItemStack(Blocks.WOOL, 1, 5), 32+(8*16), 32));
		manager.registerInfoPage("lime_wool", new GuideInfoPage("lime_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("green_wool", "Green Wool", new ItemStack(Blocks.WOOL, 1, 13), 32+(9*16), 32));
		manager.registerInfoPage("green_wool", new GuideInfoPage("green_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("cyan_wool", "Cyan Wool", new ItemStack(Blocks.WOOL, 1, 9), 32+(10*16), 32));
		manager.registerInfoPage("cyan_wool", new GuideInfoPage("cyan_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("light_blue_wool", "Light Blue Wool", new ItemStack(Blocks.WOOL, 1, 3), 32+(11*16), 32));
		manager.registerInfoPage("light_blue_wool", new GuideInfoPage("light_blue_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("blue_wool", "Blue Wool", new ItemStack(Blocks.WOOL, 1, 11), 32+(12*16), 32));
		manager.registerInfoPage("blue_wool", new GuideInfoPage("blue_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("purple_wool", "Purple Wool", new ItemStack(Blocks.WOOL, 1, 10), 32+(13*16), 32));
		manager.registerInfoPage("purple_wool", new GuideInfoPage("purple_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("magenta_wool", "Magenta Wool", new ItemStack(Blocks.WOOL, 1, 2), 32+(14*16), 32));
		manager.registerInfoPage("magenta_wool", new GuideInfoPage("magenta_wool", EnumPageType.INFO));
		misc_building.addEntry(new GuideEntry("pink_wool", "Pink Wool", new ItemStack(Blocks.WOOL, 1, 6), 32+(15*16), 32));
		manager.registerInfoPage("pink_wool", new GuideInfoPage("pink_wool", EnumPageType.INFO));
		
		wood_building.addEntry(new GuideEntry("oak_log", "Oak Wood", new ItemStack(Blocks.LOG, 1, 0), 32+(0*16), 32));
		manager.registerInfoPage("oak_log", new GuideInfoPage("oak_log", EnumPageType.INFO));
		wood_building.addEntry(new GuideEntry("spruce_log", "Spruce Wood", new ItemStack(Blocks.LOG, 1, 1), 32+(1*16), 32));
		manager.registerInfoPage("spruce_log", new GuideInfoPage("spruce_log", EnumPageType.INFO));
		wood_building.addEntry(new GuideEntry("birch_log", "Birch Wood", new ItemStack(Blocks.LOG, 1, 2), 32+(2*16), 32));
		manager.registerInfoPage("birch_log", new GuideInfoPage("birch_log", EnumPageType.INFO));
		wood_building.addEntry(new GuideEntry("jungle_log", "Jungle Wood", new ItemStack(Blocks.LOG, 1, 3), 32+(3*16), 32));
		manager.registerInfoPage("jungle_log", new GuideInfoPage("jungle_log", EnumPageType.INFO));
		wood_building.addEntry(new GuideEntry("acacia_log", "Acacia Wood", new ItemStack(Blocks.LOG2, 1, 0), 32+(4*16), 32));
		manager.registerInfoPage("acacia_log", new GuideInfoPage("acacia_log", EnumPageType.INFO));
		wood_building.addEntry(new GuideEntry("dark_oak_log", "Dark Oak Wood", new ItemStack(Blocks.LOG2, 1, 1), 32+(5*16), 32));
		manager.registerInfoPage("dark_oak_log", new GuideInfoPage("dark_oak_log", EnumPageType.INFO));
		wood_building.addEntry(new GuideEntry("oak_planks", "Oak Wood Planks", new ItemStack(Blocks.PLANKS, 1, 0), 32+(6*16), 32));
		manager.registerInfoPage("oak_planks", new GuideInfoPage("oak_planks", EnumPageType.INFO));
		wood_building.addEntry(new GuideEntry("spruce_planks", "Spruce Wood Planks", new ItemStack(Blocks.PLANKS, 1, 1), 32+(7*16), 32));
		manager.registerInfoPage("spruce_planks", new GuideInfoPage("spruce_planks", EnumPageType.INFO));
		wood_building.addEntry(new GuideEntry("birch_planks", "Birch Wood Planks", new ItemStack(Blocks.PLANKS, 1, 2), 32+(8*16), 32));
		manager.registerInfoPage("birch_planks", new GuideInfoPage("birch_planks", EnumPageType.INFO));
		wood_building.addEntry(new GuideEntry("jungle_planks", "Jungle Wood Planks", new ItemStack(Blocks.PLANKS, 1, 3), 32+(9*16), 32));
		manager.registerInfoPage("jungle_planks", new GuideInfoPage("jungle_planks", EnumPageType.INFO));
		wood_building.addEntry(new GuideEntry("acacia_planks", "Acacia Wood Planks", new ItemStack(Blocks.PLANKS, 1, 4), 32+(10*16), 32));
		manager.registerInfoPage("acacia_planks", new GuideInfoPage("acacia_planks", EnumPageType.INFO));
		wood_building.addEntry(new GuideEntry("dark_oak_planks", "Dark Oak Wood Planks", new ItemStack(Blocks.PLANKS, 1, 5), 32+(11*16), 32));
		manager.registerInfoPage("dark_oak_planks", new GuideInfoPage("dark_oak_planks", EnumPageType.INFO));
		
		stone_building.addEntry(new GuideEntry("cobblestone", "Cobblestone", new ItemStack(Blocks.COBBLESTONE), 32+(0*16), 32));
		manager.registerInfoPage("cobblestone", new GuideInfoPage("cobblestone", EnumPageType.INFO));
		stone_building.addEntry(new GuideEntry("polished_granite", "Polished Granite", new ItemStack(Blocks.STONE, 1, 2), 32+(1*16), 32));
		manager.registerInfoPage("polished_granite", new GuideInfoPage("polished_granite", EnumPageType.INFO));
		stone_building.addEntry(new GuideEntry("polished_diorite", "Polished Diorite", new ItemStack(Blocks.STONE, 1, 4), 32+(2*16), 32));
		manager.registerInfoPage("polished_diorite", new GuideInfoPage("polished_diorite", EnumPageType.INFO));		
		stone_building.addEntry(new GuideEntry("polished_andesite", "Polished Andesite", new ItemStack(Blocks.STONE, 1, 6), 32+(3*16), 32));
		manager.registerInfoPage("polished_andesite", new GuideInfoPage("polished_andesite", EnumPageType.INFO));
		stone_building.addEntry(new GuideEntry("smooth_sandstone", "Polished Sandstone", new ItemStack(Blocks.SANDSTONE, 0, 2), 32+(4*16), 32));
		manager.registerInfoPage("smooth_sandstone", new GuideInfoPage("smooth_sandstone", EnumPageType.INFO));
		stone_building.addEntry(new GuideEntry("chiseled_sandstone", "Chiseled Sandstone", new ItemStack(Blocks.SANDSTONE, 0, 1), 32+(5*16), 32));
		manager.registerInfoPage("chiseled_sandstone", new GuideInfoPage("chiseled_sandstone", EnumPageType.INFO));
		
		utility.addEntry(new GuideEntry("web", "Cobweb", new ItemStack(Blocks.WEB), 32+(0*16), 32));
		manager.registerInfoPage("web", new GuideInfoPage("web", EnumPageType.INFO));
		utility.addEntry(new GuideEntry("bed", "Bed", new ItemStack(Items.BED), 32+(1*16), 32));
		manager.registerInfoPage("bed", new GuideInfoPage("bed", EnumPageType.INFO));
		
		redstone.addEntry(new GuideEntry("golden_rail", "Powered Rail", new ItemStack(Blocks.GOLDEN_RAIL), 32+(0*16), 32));
		manager.registerInfoPage("golden_rail", new GuideInfoPage("golden_rail", EnumPageType.INFO));
		redstone.addEntry(new GuideEntry("detector_rail", "Detector Rail", new ItemStack(Blocks.DETECTOR_RAIL), 32+(1*16), 32));
		manager.registerInfoPage("detector_rail", new GuideInfoPage("detector_rail", EnumPageType.INFO));
		redstone.addEntry(new GuideEntry("piston", "Piston", new ItemStack(Blocks.PISTON), 32+(2*16), 32));
		manager.registerInfoPage("piston", new GuideInfoPage("piston", EnumPageType.INFO));
		redstone.addEntry(new GuideEntry("sticky_piston", "Sticky Piston", new ItemStack(Blocks.STICKY_PISTON), 32+(2*16), 32));
		manager.registerInfoPage("sticky_piston", new GuideInfoPage("sticky_piston", EnumPageType.INFO));
		redstone.addEntry(new GuideEntry("dispenser", "Dispenser", new ItemStack(Blocks.DISPENSER), 32+(3*16), 32));
		manager.registerInfoPage("dispenser", new GuideInfoPage("dispenser", EnumPageType.INFO));
		redstone.addEntry(new GuideEntry("noteblock", "Note Block", new ItemStack(Blocks.NOTEBLOCK), 32+(4*16), 32));
		manager.registerInfoPage("noteblock", new GuideInfoPage("noteblock", EnumPageType.INFO));
	}

}
